---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

busser:
    sudo: true

suites:
  - name: default
    excludes:
      - ubuntu-13.10
    run_list:
      - recipe[duo_unix::default]
    attributes:
  - name: attributes
    run_list:
      - recipe[duo_unix::default]
    attributes:
      duo_unix:
        conf:
          secret_key: 'fakeskeyvalue123'
          integration_key: 'fakeikeyvalue456'
          api_hostname: 'api.duounixhost.test'
          PermitTunnel: true
          AllowTCPForwarding: true
          login_duo_enabled: false
          pushinfo: 'yes'
          failmode: 'secure'
          autopush: true
          group: 'duousers'
  - name: fromsource
    run_list:
      - recipe[duo_unix::default]
    attributes:
      duo_unix:
        from_source: true
  - name: withpam
    # excluding distros where package not available
    excludes:
      - ubuntu-13.10
      - ubuntu-14.04
    run_list:
      - recipe[duo_unix::default]
    attributes:
      duo_unix:
        conf:
          pam_module: true
  - name: withpamfromsource
    excludes:
      - ubuntu-12.04
    run_list:
      - recipe[duo_unix::default]
    attributes:
      duo_unix:
        conf:
          pam_module: true
          login_duo_enabled: false
          pam_enabled: true
