---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[duo_unix::default]
    attributes:
  - name: attributes
    run_list:
      - recipe[duo_unix::default]
    attributes:
      duo_unix:
        conf:
          PermitTunnel: true
          AllowTCPForwarding: true
          login_duo_enabled: false
  - name: fromsource
    run_list:
      - recipe[duo_unix::default]
    attributes:
      duo_unix:
        from_source: true
