name             "duo_unix"
maintainer       "Hung Truong"
maintainer_email "hung@hung-truong.com"
license          "Apache 2.0"
description      "Installs/Configures Duo Unix two-factor authentication"
version          "0.7.0"
depends          "openssh"
depends          "apt"
