default['duo_unix']['url'] = 'https://dl.duosecurity.com/duo_unix-'
default['duo_unix']['version']  = '1.9.7'
default['duo_unix']['checksum'] = '8fc90eed4924cf23a8e1ea275be81f345932954a'
default['duo_unix']['configure_options'] = %W{--prefix=/usr}
default['duo_unix']['conf']['integration_key'] = ''
default['duo_unix']['conf']['secret_key'] = ''
default['duo_unix']['conf']['api_hostname'] = ''
default['duo_unix']['conf']['pushinfo'] = 'no'
default['duo_unix']['conf']['group'] = ''
default['duo_unix']['conf']['failmode'] = 'safe'
default['duo_unix']['conf']['PermitTunnel'] = false
default['duo_unix']['conf']['AllowTCPForwarding'] = false
default['duo_unix']['conf']['login_duo_enabled'] = true
